FROM mcr.microsoft.com/dotnet/core/aspnet:3.1.3-alpine3.11 AS base

WORKDIR /app

EXPOSE 80

EXPOSE 443

# environment variable 
ENV ASPNETCORE_URLS = http://*:80 

FROM mcr.microsoft.com/dotnet/core/sdk:3.1.201-alpine3.11 AS build

WORKDIR /src

COPY ["OURWebApplication/OURWebApplication.csproj", "OURWebApplication/"]

RUN dotnet clean "OURWebApplication/OURWebApplication.csproj"

RUN dotnet restore "OURWebApplication/OURWebApplication.csproj"

COPY . .

WORKDIR "/src/OURWebApplication"

RUN dotnet --info

RUN dotnet --list-sdks

RUN dotnet --list-runtimes

RUN find -type d -name bin -prune -exec rm -rf {} \; && find -type d -name obj -prune -exec rm -rf {} \;

RUN dotnet build "OURWebApplication.csproj" -c Release -o /app/build



FROM build AS publish

RUN dotnet publish "OURWebApplication.csproj" -c Release -o /app/publish



FROM base AS final

WORKDIR /app

COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "OURWebApplication.dll"]
