---
 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
   annotations:
   labels:
     run: dotnet-app-ui
   name: dotnet-app-ui
 spec:
   progressDeadlineSeconds: 600
   replicas: 1
   revisionHistoryLimit: 10
   selector:
     matchLabels:
       run: dotnet-app-ui
   strategy:
     rollingUpdate:
       maxSurge: 25%
       maxUnavailable: 25%
     type: RollingUpdate
   template:
     metadata:
       labels:
         run: dotnet-app-ui
     spec:
       containers:
       - image: 1234567890.dkr.ecr.us-east-1.amazonaws.com/dotnet-app-ui:v1.0
         imagePullPolicy: Always
         name: dotnet-app-ui
         env:
         - name: ASPNETCORE_ENVIRONMENT
           value: production
         - name: ENV_variable2
           value: "value2"
         ports:
         - containerPort: 80
           protocol: TCP
         resources:
           limits:
             cpu: 1000m
             memory: 1000M
           requests:
             cpu: 750m
             memory: 1000M
         terminationMessagePath: /dev/termination-log
         terminationMessagePolicy: File
         readinessProbe:
           httpGet:
             port: 80
             path: /
             scheme: HTTP
           initialDelaySeconds: 180
           periodSeconds: 10
           timeoutSeconds: 60
           failureThreshold: 2
           successThreshold: 4
         livenessProbe:
           httpGet:
             port: 80
             path: /
             scheme: HTTP
           initialDelaySeconds: 180
           periodSeconds: 10
           failureThreshold: 2
           timeoutSeconds: 60
       dnsPolicy: ClusterFirst
       imagePullSecrets:
       - name: us-west-2-ecr-registry
       restartPolicy: Always
       schedulerName: default-scheduler
       securityContext: {}
       terminationGracePeriodSeconds: 30
---
 apiVersion: v1
 kind: Service
 metadata:
   labels:
     run: dotnet-app-ui
   name: dotnet-app-ui
 spec:
   ports:
   - port: 80
     protocol: TCP
     targetPort: 80
   selector:
     run: dotnet-app-ui
   sessionAffinity: None
   type: NodePort
